version: "3.9"
services:
  postgres:
    container_name: database
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: 
      - '5432:5432'
    volumes:
      - postgres-db:/var/lib/postgresql/data

  culture-dao:
    container_name: frontend
    build:
      context: .
      dockerfile: ./docker/culture-dao/Dockerfile.dev
    environment:
      DB_SCHEMA: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
    depends_on:
      - postgres
    ports:
      - '3000:3000'

volumes:
  postgres-db: